export const ALL_USERS_TABLE = "ALL_USERS_TABLE";

export const PATIENTS_TABLE = "PATIENTS_TABLE";

export const DOCTORS_TABLE = "DOCTORS_TABLE";

export const HEALTH_OFFICIALS_TABLE = "HEALTH_OFFICIALS_TABLE";

export const IMMIGRATION_OFFICERS_TABLE = "IMMIGRATION_OFFICERS_TABLE";

export const ADMINS_TABLE = "ADMINS_TABLE";

export const CARD_DETAILS = "CARD_DETAILS";

export const BUSINESSES_TABLE = "BUSINESSES_TABLE";

export const SEE_MY_PATIENTS_TABLE = "SEE_MY_PATIENTS_TABLE";
